import React, { useMemo, useState } from "react";
import { AlertTriangle, Beaker, CalendarClock, CheckCircle2, ClipboardCheck, Cpu, FileCheck2, FlaskConical, Gauge, Search, ShieldAlert, ShieldCheck, SlidersHorizontal, Timer, XCircle } from "lucide-react";
import type { CalibrationRecord, SampleRecord, TestDeviceRecord } from "../types/qualityDomain";
import { buildCalibrationAlerts, buildSampleTraceRows, LABORATORY_CAPABILITIES, summarizeQualityAssets, type QualityAssetMetric, type QualityTestRecord } from "../services/qualityAssetAnalytics";

type Language = "ar" | "fr" | "en";
const c = (l: Language, ar: string, fr: string, en: string) => l === "ar" ? ar : l === "fr" ? fr : en;
const labelMetric = (l: Language, state: QualityAssetMetric) => ({ valid: c(l, "ساري", "Valide", "Valid"), due: c(l, "يستحق قريبًا", "À échéance", "Due soon"), expired: c(l, "منتهي", "Expiré", "Expired"), unknown: c(l, "غير معروف", "Inconnu", "Unknown") }[state]);
const metricClass = (state: QualityAssetMetric) => state === "valid" ? "bg-emerald-100 text-emerald-700" : state === "due" ? "bg-amber-100 text-amber-700" : state === "expired" ? "bg-rose-100 text-rose-700" : "bg-slate-100 text-slate-600";
const sampleClass = (state: "complete" | "partial" | "missing") => state === "complete" ? "bg-emerald-100 text-emerald-700" : state === "partial" ? "bg-amber-100 text-amber-700" : "bg-rose-100 text-rose-700";

interface Props {
  language: Language;
  samples: SampleRecord[];
  tests: QualityTestRecord[];
  devices: TestDeviceRecord[];
  calibrations: CalibrationRecord[];
}

type View = "overview" | "samples" | "tests" | "devices" | "capabilities";

export const QualityAssetsDashboard: React.FC<Props> = ({ language, samples = [], tests = [], devices = [], calibrations = [] }) => {
  const [view, setView] = useState<View>("overview");
  const [query, setQuery] = useState("");
  const now = useMemo(() => new Date(), []);
  const summary = useMemo(() => summarizeQualityAssets(samples, tests, devices, calibrations, now), [samples, tests, devices, calibrations, now]);
  const alerts = useMemo(() => buildCalibrationAlerts(devices, now), [devices, now]);
  const traceRows = useMemo(() => buildSampleTraceRows(samples, tests), [samples, tests]);
  const filteredSamples = traceRows.filter(row => `${row.sampleNumber} ${row.id} ${row.projectId || ""} ${row.batchId || ""}`.toLowerCase().includes(query.toLowerCase()));
  const filteredTests = tests.filter(test => `${test.id} ${test.sampleId} ${test.testType} ${test.standard}`.toLowerCase().includes(query.toLowerCase()));
  const filteredDevices = alerts.filter(alert => `${alert.device.name} ${alert.device.id} ${alert.device.serialNumber || ""} ${alert.device.deviceType}`.toLowerCase().includes(query.toLowerCase()));
  const tabs: Array<{ id: View; icon: React.ComponentType<{ size?: number }>; ar: string; fr: string; en: string }> = [
    { id: "overview", icon: Gauge, ar: "نظرة تشغيلية", fr: "Vue opérationnelle", en: "Operations overview" },
    { id: "samples", icon: Beaker, ar: "العينات والتتبع", fr: "Échantillons et traçabilité", en: "Samples & traceability" },
    { id: "tests", icon: ClipboardCheck, ar: "سجل الاختبارات", fr: "Registre des essais", en: "Test register" },
    { id: "devices", icon: Cpu, ar: "الأجهزة والمعايرة", fr: "Appareils et étalonnage", en: "Devices & calibration" },
    { id: "capabilities", icon: FlaskConical, ar: "قدرات المختبر", fr: "Capacités du laboratoire", en: "Lab capabilities" }
  ];
  const statusLabel = (status: string) => ({ received: c(language, "مستلمة", "Reçue", "Received"), "in-testing": c(language, "قيد الاختبار", "En essai", "In testing"), accepted: c(language, "مقبولة", "Acceptée", "Accepted"), rejected: c(language, "مرفوضة", "Rejetée", "Rejected"), archived: c(language, "مؤرشفة", "Archivée", "Archived") } as Record<string, string>)[status] || status;
  const approvalLabel = (status: string) => ({ draft: c(language, "مسودة", "Brouillon", "Draft"), submitted: c(language, "مرسلة للمراجعة", "Soumise", "Submitted"), approved: c(language, "معتمدة", "Approuvée", "Approved"), rejected: c(language, "مرفوضة", "Rejetée", "Rejected") } as Record<string, string>)[status] || status;

  return <section dir={language === "ar" ? "rtl" : "ltr"} className="space-y-5" data-testid="quality-assets-dashboard">
    <header className="relative overflow-hidden rounded-3xl bg-slate-950 p-6 text-white shadow-xl">
      <div className="absolute -end-12 -top-16 h-56 w-56 rounded-full bg-cyan-500/20 blur-3xl" />
      <div className="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between">
        <div>
          <div className="mb-2 flex items-center gap-2 text-[10px] font-black tracking-[.18em] text-cyan-300"><ShieldCheck size={15} /> SNOLAB · CIVIL LAB OPERATIONS</div>
          <h1 className="text-2xl font-black tracking-tight">{c(language, "مركز عمليات المختبر المدني", "Centre des opérations du laboratoire civil", "Civil laboratory operations center")}</h1>
          <p className="mt-2 max-w-3xl text-xs leading-6 text-slate-300">{c(language, "من استقبال العينة وسلسلة الحيازة إلى صلاحية الجهاز واعتماد النتيجة — لوحة واحدة لاتخاذ قرار هندسي قابل للتتبع.", "De la réception de l’échantillon à l’approbation du résultat — un centre unique et traçable.", "From sample intake to result approval — one traceable workspace for engineering release decisions.")}</p>
        </div>
        <div className="flex items-center gap-2 rounded-2xl border border-white/10 bg-white/5 px-3 py-2 text-[10px] text-slate-300"><Timer size={15} className="text-cyan-300" /> {c(language, "حالة البيانات: محلية وقابلة للمراجعة", "Données locales et auditables", "Local and auditable data")}</div>
      </div>
    </header>

    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-8">
      {[
        [Beaker, c(language, "عينات نشطة", "Échantillons actifs", "Active samples"), summary.activeSamples, "text-cyan-600"],
        [FileCheck2, c(language, "اختبارات", "Essais", "Tests"), summary.tests, "text-indigo-600"],
        [CheckCircle2, c(language, "اختبارات معتمدة", "Essais approuvés", "Approved tests"), summary.approvedTests, "text-emerald-600"],
        [ShieldAlert, c(language, "اختبارات قيد المراجعة", "Essais à revoir", "Tests pending"), summary.pendingTests, "text-amber-600"],
        [Cpu, c(language, "أجهزة سارية", "Appareils valides", "Valid devices"), summary.validDevices, "text-emerald-600"],
        [AlertTriangle, c(language, "معايرة قريبة", "Étalonnages proches", "Calibration due"), summary.dueDevices, "text-amber-600"],
        [XCircle, c(language, "معايرة منتهية", "Étalonnages expirés", "Calibration expired"), summary.expiredDevices, "text-rose-600"],
        [ShieldCheck, c(language, "اكتمال التتبع", "Traçabilité complète", "Traceability"), `${summary.traceabilityRate}%`, "text-blue-600"]
      ].map(([Icon, label, value, tone]) => <div key={String(label)} className="flex items-center gap-3 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm dark:border-slate-800 dark:bg-slate-900/70"><Icon size={19} className={String(tone)} /><div className="min-w-0"><div className="truncate text-[10px] font-bold text-slate-500">{String(label)}</div><div className="text-xl font-black text-slate-900 dark:text-white">{String(value)}</div></div></div>)}
    </div>

    <div className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm dark:border-slate-800 dark:bg-slate-900/70 lg:flex-row lg:items-center lg:justify-between">
      <div className="flex flex-wrap gap-1">{tabs.map(tab => { const Icon = tab.icon; return <button key={tab.id} type="button" onClick={() => setView(tab.id)} className={`inline-flex items-center gap-2 rounded-xl px-3 py-2 text-[11px] font-black transition ${view === tab.id ? "bg-indigo-600 text-white shadow" : "text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800"}`}><Icon size={15} />{c(language, tab.ar, tab.fr, tab.en)}</button>; })}</div>
      {view !== "overview" && <label className="flex items-center gap-2 rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 dark:border-slate-700 dark:bg-slate-950"><Search size={15} className="text-slate-400" /><input value={query} onChange={event => setQuery(event.target.value)} className="w-full bg-transparent text-xs outline-none lg:w-64" placeholder={c(language, "بحث في السجل…", "Rechercher…", "Search register…")} /></label>}
    </div>

    {view === "overview" && <div className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]">
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900/70"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-sm font-black">{c(language, "قائمة الانتباه التشغيلية", "File d’attention opérationnelle", "Operational attention queue")}</h2><p className="mt-1 text-[11px] text-slate-500">{c(language, "عالج الحالات الأعلى خطورة قبل إصدار النتيجة.", "Traiter les risques avant la libération.", "Resolve high-risk items before release.")}</p></div><SlidersHorizontal size={18} className="text-indigo-500" /></div><div className="space-y-2">{alerts.filter(item => item.state !== "valid").slice(0, 5).map(item => <div key={item.device.id} className="flex items-center justify-between rounded-xl border border-slate-100 bg-slate-50 p-3 text-xs dark:border-slate-800 dark:bg-slate-950"><div className="flex items-center gap-2"><AlertTriangle size={15} className={item.state === "expired" ? "text-rose-600" : "text-amber-600"} /><span className="font-bold">{item.device.name}</span><span className="font-mono text-[10px] text-slate-400">{item.device.serialNumber || item.device.id}</span></div><span className={`rounded-full px-2 py-1 text-[10px] font-black ${metricClass(item.state)}`}>{labelMetric(language, item.state)}</span></div>)}{summary.pendingTests > 0 && <div className="flex items-center justify-between rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900"><span className="font-bold">{c(language, `${summary.pendingTests} نتيجة تحتاج مراجعة واعتماد`, `${summary.pendingTests} résultat(s) à revoir`, `${summary.pendingTests} result(s) pending approval`)}</span><button type="button" onClick={() => setView("tests")} className="rounded-lg bg-amber-600 px-3 py-1.5 text-[10px] font-black text-white">{c(language, "فتح السجل", "Ouvrir", "Open")}</button></div>}{!alerts.some(item => item.state !== "valid") && summary.pendingTests === 0 && <div className="rounded-xl bg-emerald-50 p-4 text-xs font-bold text-emerald-800"><CheckCircle2 className="mb-1 inline" size={15} /> {c(language, "لا توجد حالات حرجة في قائمة الانتباه.", "Aucune alerte critique.", "No critical attention items.")}</div>}</div></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900/70"><h2 className="text-sm font-black">{c(language, "جاهزية المختبر للإصدار", "Préparation à la libération", "Release readiness")}</h2><div className="mt-4 space-y-4"><div><div className="mb-1 flex justify-between text-[11px] font-bold"><span>{c(language, "اكتمال سلسلة الحيازة", "Chaîne de garde", "Chain of custody")}</span><span>{summary.traceabilityRate}%</span></div><div className="h-2 rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-2 rounded-full bg-cyan-500" style={{ width: `${summary.traceabilityRate}%` }} /></div></div><div><div className="mb-1 flex justify-between text-[11px] font-bold"><span>{c(language, "معدل نجاح المعايرات", "Réussite étalonnage", "Calibration pass rate")}</span><span>{summary.calibrationPassRate}%</span></div><div className="h-2 rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-2 rounded-full bg-emerald-500" style={{ width: `${summary.calibrationPassRate}%` }} /></div></div><div className="grid grid-cols-2 gap-2 pt-2 text-center"><div className="rounded-xl bg-indigo-50 p-3 text-indigo-800"><div className="text-xl font-black">{summary.acceptedSamples}</div><div className="text-[10px]">{c(language, "عينات مقبولة", "Échantillons acceptés", "Accepted samples")}</div></div><div className="rounded-xl bg-rose-50 p-3 text-rose-800"><div className="text-xl font-black">{summary.rejectedSamples}</div><div className="text-[10px]">{c(language, "عينات مرفوضة", "Échantillons rejetés", "Rejected samples")}</div></div></div></div></section>
    </div>}

    {view === "samples" && <DataSection title={c(language, "سجل العينات وسلسلة الحيازة", "Registre des échantillons", "Sample & chain-of-custody register")}><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-xs"><thead className="border-b border-slate-200 text-[10px] text-slate-500"><tr><th className="p-2 text-start">ID</th><th className="p-2 text-start">{c(language, "رقم العينة", "N° échantillon", "Sample no.")}</th><th className="p-2 text-start">{c(language, "الوصول", "Réception", "Received")}</th><th className="p-2 text-start">{c(language, "الاختبارات المرتبطة", "Essais liés", "Linked tests")}</th><th className="p-2 text-start">{c(language, "الحالة", "État", "Status")}</th><th className="p-2 text-start">{c(language, "التتبع", "Traçabilité", "Traceability")}</th></tr></thead><tbody>{filteredSamples.map(row => <tr key={row.id} className="border-b border-slate-100 dark:border-slate-800"><td className="p-2 font-mono">{row.id}</td><td className="p-2 font-bold">{row.sampleNumber}</td><td className="p-2">{row.receivedAt || "—"}</td><td className="p-2">{row.linkedTestCount}</td><td className="p-2">{statusLabel(row.status)}</td><td className="p-2"><span className={`rounded-full px-2 py-1 text-[10px] font-black ${sampleClass(row.traceabilityState)}`}>{c(language, row.traceabilityState === "complete" ? "مكتمل" : row.traceabilityState === "partial" ? "جزئي" : "مفقود", row.traceabilityState === "complete" ? "Complet" : row.traceabilityState === "partial" ? "Partiel" : "Manquant", row.traceabilityState)}</span></td></tr>)}{!filteredSamples.length && <EmptyRow colSpan={6} language={language} />}</tbody></table></div></DataSection>}

    {view === "tests" && <DataSection title={c(language, "سجل الاختبارات والاعتماد", "Registre des essais et approbations", "Test & approval register")}><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-xs"><thead className="border-b border-slate-200 text-[10px] text-slate-500"><tr><th className="p-2 text-start">ID</th><th className="p-2 text-start">{c(language, "العينة", "Échantillon", "Sample")}</th><th className="p-2 text-start">{c(language, "الاختبار", "Essai", "Test")}</th><th className="p-2 text-start">{c(language, "المواصفة", "Norme", "Standard")}</th><th className="p-2 text-start">{c(language, "الجهاز", "Appareil", "Device")}</th><th className="p-2 text-start">{c(language, "الاعتماد", "Approbation", "Approval")}</th></tr></thead><tbody>{filteredTests.map(test => <tr key={test.id} className="border-b border-slate-100 dark:border-slate-800"><td className="p-2 font-mono">{test.id}</td><td className="p-2">{test.sampleId}</td><td className="p-2 font-bold">{test.testType}</td><td className="p-2">{test.standard}</td><td className="p-2">{test.deviceId || "—"}</td><td className="p-2"><span className={`rounded-full px-2 py-1 text-[10px] font-black ${test.approvalStatus === "approved" ? "bg-emerald-100 text-emerald-700" : test.approvalStatus === "rejected" ? "bg-rose-100 text-rose-700" : "bg-amber-100 text-amber-700"}`}>{approvalLabel(test.approvalStatus)}</span></td></tr>)}{!filteredTests.length && <EmptyRow colSpan={6} language={language} />}</tbody></table></div></DataSection>}

    {view === "devices" && <DataSection title={c(language, "الأجهزة وشهادات المعايرة", "Appareils et certificats", "Devices & calibration certificates")}><div className="grid gap-3 md:grid-cols-2">{filteredDevices.map(alert => <div key={alert.device.id} className="rounded-2xl border border-slate-200 p-4 dark:border-slate-800"><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-2"><Cpu size={18} className="text-indigo-600" /><div><div className="text-sm font-black">{alert.device.name}</div><div className="font-mono text-[10px] text-slate-500">{alert.device.serialNumber || alert.device.id} · {alert.device.deviceType}</div></div></div><span className={`rounded-full px-2 py-1 text-[10px] font-black ${metricClass(alert.state)}`}>{labelMetric(language, alert.state)}</span></div><div className="mt-4 grid grid-cols-2 gap-2 text-[10px]"><div className="rounded-xl bg-slate-50 p-2 dark:bg-slate-950"><div className="text-slate-500">{c(language, "الاستحقاق", "Échéance", "Due date")}</div><div className="mt-1 font-bold">{alert.dueAt || "—"}</div></div><div className="rounded-xl bg-slate-50 p-2 dark:bg-slate-950"><div className="text-slate-500">{c(language, "الأيام المتبقية", "Jours restants", "Days remaining")}</div><div className="mt-1 font-bold">{alert.daysToDue ?? "—"}</div></div></div></div>)}{!filteredDevices.length && <div className="rounded-xl border border-dashed border-slate-200 p-10 text-center text-xs text-slate-500 dark:border-slate-800">{c(language, "لا توجد أجهزة مطابقة.", "Aucun appareil correspondant.", "No matching devices.")}</div>}</div></DataSection>}

    {view === "capabilities" && <DataSection title={c(language, "مصفوفة قدرات SnoLab المختبرية", "Matrice des capacités SnoLab", "SnoLab laboratory capability matrix")}><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{LABORATORY_CAPABILITIES.map(capability => <article key={capability.id} className="rounded-2xl border border-slate-200 bg-slate-50 p-4 dark:border-slate-800 dark:bg-slate-950"><div className="flex items-start justify-between gap-3"><div><h3 className="text-sm font-black">{c(language, capability.ar, capability.fr, capability.en)}</h3><p className="mt-2 text-[11px] leading-5 text-slate-500">{capability.standard}</p></div><CheckCircle2 size={18} className="text-emerald-600" /></div><div className="mt-4 flex items-center gap-2 text-[10px] font-bold text-emerald-700"><ShieldCheck size={14} /> {c(language, "متاحة ضمن سير العمل الحالي", "Disponible dans le flux actuel", "Available in current workflow")}</div></article>)}</div></DataSection>}
  </section>;
};

const DataSection: React.FC<React.PropsWithChildren<{ title: string }>> = ({ title, children }) => <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900/70"><div className="mb-4 flex items-center gap-2"><FileCheck2 size={18} className="text-indigo-600" /><h2 className="text-sm font-black">{title}</h2></div>{children}</section>;
const EmptyRow: React.FC<{ colSpan: number; language: Language }> = ({ colSpan, language }) => <tr><td colSpan={colSpan} className="p-10 text-center text-xs text-slate-500">{c(language, "لا توجد سجلات مطابقة.", "Aucun enregistrement correspondant.", "No matching records.")}</td></tr>;
