import React, { useMemo } from "react";
import { ArrowRightLeft, LockKeyhole } from "lucide-react";
import { MixVersion } from "../types";
interface Props { versions: MixVersion[]; }
const fields: Array<[string,string]> = [["fck28","fck28"],["slump","slump"],["dMax","dMax"],["moistureSand","sand moisture"],["moistureGravel","gravel moisture"],["cementWeight","cement"],["waterContentActual","actual water"],["sandWeightWet","wet sand"],["gravelWeightWet","wet gravel"]];
export const RevisionDiffPanel: React.FC<Props> = ({ versions }) => {
  const rows = useMemo(() => fields.map(([key,label]) => { const values=versions.map(v => (v.inputs as any)?.[key] ?? (v.results as any)?.[key]); const changed = new Set(values.map(v=>JSON.stringify(v))).size > 1; return {key,label,values,changed}; }), [versions]);
  if (versions.length < 2) return <div className="rounded-2xl border border-dashed border-slate-300 p-5 text-center text-xs text-slate-500">حدد إصدارين أو أكثر لعرض Revision Diff.</div>;
  return <section className="rounded-2xl border border-indigo-200 bg-indigo-50/40 p-5 text-right dark:border-indigo-900/50 dark:bg-indigo-950/20" dir="rtl" data-testid="revision-diff-panel"><div className="mb-4 flex items-center justify-between border-b border-indigo-100 pb-3 dark:border-indigo-900"><h4 className="flex items-center gap-2 text-sm font-black text-indigo-950 dark:text-indigo-100"><ArrowRightLeft size={17}/> مقارنة Revision التفصيلية</h4><span className="text-[10px] font-bold text-indigo-600">{versions.length} versions / immutable snapshots</span></div><div className="mb-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{versions.map(v=><div key={v.id} className="rounded-xl border border-indigo-100 bg-white p-3 dark:border-indigo-900 dark:bg-slate-900"><div className="text-xs font-black">{v.name}</div><div className="mt-1 text-[10px] text-slate-500">REV {v.revisionNumber||1} · {v.lifecycleStatus||"draft"}</div><div className="mt-1 truncate font-mono text-[9px] text-slate-400">{v.immutableHash||"no hash"}</div></div>)}</div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-xs"><thead className="border-b border-indigo-100 text-[10px] text-slate-500"><tr><th className="p-2 text-start">Field</th>{versions.map(v=><th key={v.id} className="p-2 text-center">{v.name}</th>)}<th className="p-2 text-center">Change</th></tr></thead><tbody>{rows.map(row=><tr key={row.key} className={row.changed?"border-b border-amber-100 bg-amber-50/70":"border-b border-slate-100"}><td className="p-2 font-bold">{row.label}</td>{row.values.map((v,i)=><td key={i} className="p-2 text-center font-mono">{v === undefined || v === null ? "—" : String(v)}</td>)}<td className="p-2 text-center font-black">{row.changed?"CHANGED":"—"}</td></tr>)}</tbody></table></div><div className="mt-4 flex items-center gap-2 text-[10px] font-bold text-slate-600"><LockKeyhole size={14} className="text-emerald-600"/> النسخ المعتمدة لا تُعدّل؛ أي فرق يؤدي إلى Revision جديدة.</div></section>;
};
