import os, sys

content = open("scripts/generate_schemas_file.py", "r").read()

# We will generate the MATERIAL_PROPERTY_SCHEMAS dictionary in TypeScript
schemas_ts = """
export const MATERIAL_PROPERTY_SCHEMAS: Record<SupportedMaterialRole, MaterialPropertyDefinition[]> = {
  // --------------------------------------------------------------------------
  // 1. CEMENT (إسمنت)
  // --------------------------------------------------------------------------
  cement: [
    {
      key: "cementClass",
      propertyId: "PROP_CEM_CLASS",
      labelAr: "نوع ورتبة الإسمنت القياسية",
      labelFr: "Type et Classe de Ciment",
      labelEn: "Cement Type & Class",
      unit: "",
      inputType: "select",
      categoryGroup: "composition",
      requirementLevel: "required",
      testStandard: "EN 197-1 / ASTM C150",
      options: [
        { value: "CEM I 42.5", labelAr: "CEM I 42.5 (بورتلاندي عادي)", labelFr: "CEM I 42.5 (Portland pur)", labelEn: "CEM I 42.5 (Ordinary Portland)" },
        { value: "CEM I 52.5", labelAr: "CEM I 52.5 (عالي المقاومة المبكرة)", labelFr: "CEM I 52.5 (Haute résistance)", labelEn: "CEM I 52.5 (High Early Strength)" },
        { value: "CEM II/A 42.5", labelAr: "CEM II/A 42.5 (مركب نوع A)", labelFr: "CEM II/A 42.5 (Composé)", labelEn: "CEM II/A 42.5 (Composite)" },
        { value: "CEM II/B 32.5", labelAr: "CEM II/B 32.5 (مركب نوع B)", labelFr: "CEM II/B 32.5 (Composé B)", labelEn: "CEM II/B 32.5 (Composite B)" },
        { value: "CEM III 42.5", labelAr: "CEM III 42.5 (خبث أفران)", labelFr: "CEM III 42.5 (Haut fourneau)", labelEn: "CEM III 42.5 (Blast Furnace)" },
        { value: "CEM IV 32.5", labelAr: "CEM IV 32.5 (بوزولاني)", labelFr: "CEM IV 32.5 (Pouzzolanique)", labelEn: "CEM IV 32.5 (Pozzolanic)" },
        { value: "CEM V 32.5", labelAr: "CEM V 32.5 (مركب)", labelFr: "CEM V 32.5 (Composite)", labelEn: "CEM V 32.5 (Composite V)" },
        { value: "White CEM I 52.5", labelAr: "CEM I 52.5 (أبيض فائق البياض)", labelFr: "CEM I 52.5 Blanc", labelEn: "White CEM I 52.5" }
      ],
      placeholder: "e.g. CEM I 42.5",
      categoryKey: "cement",
      isRequired: () => true,
      validate: (val) => (!val || String(val).trim() === "" ? { isValid: false, errorAr: "نوع الإسمنت إلزامي.", errorEn: "Cement type is required." } : { isValid: true }),
      mapToInputKeys: ["cementType"]
    },
    {
      key: "strengthClass",
      propertyId: "PROP_CEM_STRENGTH_28D",
      labelAr: "فئة المقاومة القياسية (28 يوم)",
      labelFr: "Classe de Résistance (28j)",
      labelEn: "Strength Class (28-day)",
      unit: "MPa",
      inputType: "number",
      categoryGroup: "mechanical",
      requirementLevel: "required",
      testStandard: "EN 196-1 / ASTM C109",
      associatedLabTestId: "CEM_STRENGTH",
      min: 20,
      max: 80,
      step: 0.5,
      defaultVal: 42.5,
      placeholder: "42.5",
      categoryKey: "cement",
      isRequired: () => true,
      validate: (val) => validateNumericRange(val, 20, 80, "فئة المقاومة", "Classe de résistance", "Strength class", "MPa"),
      mapToInputKeys: ["cementClass"]
    },
    {
      key: "density",
      propertyId: "PROP_CEM_DENSITY",
      labelAr: "الكثافة المطلقة للإسمنت",
      labelFr: "Masse Volumique Réelle du Ciment",
      labelEn: "Absolute Density of Cement",
      unit: "kg/m³",
      inputType: "number",
      categoryGroup: "physical",
      requirementLevel: "required",
      testStandard: "EN 196-6 / ASTM C188",
      associatedLabTestId: "CEM_DENSITY",
      min: 2800,
      max: 3300,
      step: 10,
      defaultVal: 3100,
      placeholder: "3100",
      categoryKey: "cement",
      isRequired: () => true,
      validate: (val) => validateNumericRange(val, 2800, 3300, "الكثافة الحقيقية للإسمنت", "Masse volumique réelle", "Absolute density", "kg/m³"),
      mapToInputKeys: ["cementDensity"]
    },
    {
      key: "specificGravity",
      propertyId: "PROP_CEM_SPECIFIC_GRAVITY",
      labelAr: "الوزن النوعي النسبي للإسمنت",
      labelFr: "Densité Relative du Ciment",
      labelEn: "Specific Gravity of Cement",
      unit: "",
      inputType: "number",
      categoryGroup: "physical",
      requirementLevel: "required",
      testStandard: "EN 196-6 / ASTM C188",
      min: 2.8,
      max: 3.3,
      step: 0.01,
      defaultVal: 3.10,
      placeholder: "3.10",
      categoryKey: "cement",
      isRequired: () => true,
      validate: (val) => validateNumericRange(val, 2.8, 3.3, "الوزن النوعي للإسمنت", "Densité relative", "Specific gravity", "")
    },
    {
      key: "bulkDensity",
      propertyId: "PROP_CEM_BULK_DENSITY",
      labelAr: "الكثافة الظاهرية (الصب الحر)",
      labelFr: "Masse Volumique Apparente",
      labelEn: "Bulk Density (Loose)",
      unit: "kg/m³",
      inputType: "number",
      categoryGroup: "physical",
      requirementLevel: "required",
      testStandard: "EN 1097-3",
      min: 800,
      max: 1500,
      step: 10,
      defaultVal: 1150,
      placeholder: "1150",
      categoryKey: "cement",
      isRequired: () => true,
      validate: (val) => validateNumericRange(val, 800, 1500, "الكثافة الظاهرية للإسمنت", "Masse volumique apparente", "Bulk density", "kg/m³")
    },
    {
      key: "blaineFineness",
      propertyId: "PROP_CEM_BLAINE",
      labelAr: "النعومة النوعية (سطح بلين)",
      labelFr: "Surface Spécifique Blaine (SSB)",
      labelEn: "Blaine Specific Surface Area",
      unit: "cm²/g",
      inputType: "number",
      categoryGroup: "physical",
      requirementLevel: "required",
      testStandard: "EN 196-6 / ASTM C204",
      associatedLabTestId: "CEM_BLAINE",
      min: 2500,
      max: 6500,
      step: 50,
      defaultVal: 3500,
      placeholder: "3500",
      categoryKey: "cement",
      isRequired: () => true,
      validate: (val) => validateNumericRange(val, 2500, 6500, "سطح بلين النوعي", "Surface Blaine", "Blaine fineness", "cm²/g")
    },
    {
      key: "standardConsistency",
      propertyId: "PROP_CEM_CONSISTENCY",
      labelAr: "القوام القياسي للخلط (فيكات)",
      labelFr: "Consistance Normalisée (Vicat)",
      labelEn: "Standard Consistency (Water %)",
      unit: "%",
      inputType: "number",
      categoryGroup: "hydration",
      requirementLevel: "required",
      testStandard: "EN 196-3 / ASTM C187",
      min: 20,
      max: 40,
      step: 0.1,
      defaultVal: 26.5,
      placeholder: "26.5",
      categoryKey: "cement",
      isRequired: () => true,
      validate: (val) => validateNumericRange(val, 20, 40, "القوام القياسي", "Consistance normalisée", "Standard consistency", "%")
    },
    {
      key: "initialSetting",
      propertyId: "PROP_CEM_INIT_SETTING",
      labelAr: "زمن بداية الشك (فيكات)",
      labelFr: "Début de Prise (Vicat)",
      labelEn: "Initial Setting Time",
      unit: "min",
      inputType: "number",
      categoryGroup: "hydration",
      requirementLevel: "required",
      testStandard: "EN 196-3 / ASTM C191",
      associatedLabTestId: "CEM_SETTING",
      min: 45,
      max: 360,
      step: 5,
      defaultVal: 135,
      placeholder: "135",
      categoryKey: "cement",
      isRequired: () => true,
      validate: (val) => validateNumericRange(val, 45, 360, "زمن بداية الشك", "Début de prise", "Initial setting", "min")
    },
    {
      key: "finalSetting",
      propertyId: "PROP_CEM_FINAL_SETTING",
      labelAr: "زمن نهاية الشك",
      labelFr: "Fin de Prise",
      labelEn: "Final Setting Time",
      unit: "min",
      inputType: "number",
      categoryGroup: "hydration",
      requirementLevel: "required",
      testStandard: "EN 196-3 / ASTM C191",
      associatedLabTestId: "CEM_SETTING",
      min: 90,
      max: 480,
      step: 5,
      defaultVal: 210,
      placeholder: "210",
      categoryKey: "cement",
      isRequired: () => true,
      validate: (val) => validateNumericRange(val, 90, 480, "زمن نهاية الشك", "Fin de prise", "Final setting", "min")
    },
    {
      key: "soundness",
      propertyId: "PROP_CEM_SOUNDNESS",
      labelAr: "ثبات الحجم والانتفاخ (لو شاتولييه)",
      labelFr: "Stabilité / Expansion (Le Chatelier)",
      labelEn: "Soundness / Expansion (Le Chatelier)",
      unit: "mm",
      inputType: "number",
      categoryGroup: "durability",
      requirementLevel: "required",
      testStandard: "EN 196-3",
      min: 0,
      max: 10,
      step: 0.1,
      defaultVal: 1.2,
      placeholder: "1.2",
      categoryKey: "cement",
      isRequired: () => true,
      validate: (val) => validateNumericRange(val, 0, 10, "ثبات الحجم", "Stabilité", "Soundness", "mm", true)
    },
    {
      key: "strength2d",
      propertyId: "PROP_CEM_STRENGTH_2D",
      labelAr: "مقاومة الضغط بعد يومين",
      labelFr: "Résistance à la Compression (2j)",
      labelEn: "Compressive Strength (2-day)",
      unit: "MPa",
      inputType: "number",
      categoryGroup: "mechanical",
      requirementLevel: "required",
      testStandard: "EN 196-1 / ASTM C109",
      min: 10,
      max: 45,
      step: 0.5,
      defaultVal: 21.5,
      placeholder: "21.5",
      categoryKey: "cement",
      isRequired: () => true,
      validate: (val) => validateNumericRange(val, 10, 45, "مقاومة 2 يوم", "Résistance 2j", "Strength 2d", "MPa")
    },
    {
      key: "strength7d",
      propertyId: "PROP_CEM_STRENGTH_7D",
      labelAr: "مقاومة الضغط بعد 7 أيام",
      labelFr: "Résistance à la Compression (7j)",
      labelEn: "Compressive Strength (7-day)",
      unit: "MPa",
      inputType: "number",
      categoryGroup: "mechanical",
      requirementLevel: "required",
      testStandard: "EN 196-1 / ASTM C109",
      min: 18,
      max: 60,
      step: 0.5,
      defaultVal: 33.0,
      placeholder: "33.0",
      categoryKey: "cement",
      isRequired: () => true,
      validate: (val) => validateNumericRange(val, 18, 60, "مقاومة 7 أيام", "Résistance 7j", "Strength 7d", "MPa")
    },
    {
      key: "strength28d",
      propertyId: "PROP_CEM_STRENGTH_28D_TEST",
      labelAr: "مقاومة الضغط بعد 28 يوم",
      labelFr: "Résistance à la Compression (28j)",
      labelEn: "Compressive Strength (28-day)",
      unit: "MPa",
      inputType: "number",
      categoryGroup: "mechanical",
      requirementLevel: "required",
      testStandard: "EN 196-1 / ASTM C109",
      min: 30,
      max: 80,
      step: 0.5,
      defaultVal: 48.5,
      placeholder: "48.5",
      categoryKey: "cement",
      isRequired: () => true,
      validate: (val) => validateNumericRange(val, 30, 80, "مقاومة 28 يوم", "Résistance 28j", "Strength 28d", "MPa")
    },
    {
      key: "heatOfHydration",
      propertyId: "PROP_CEM_HEAT_HYDRATION",
      labelAr: "حرارة الإماهة (7 أيام)",
      labelFr: "Chaleur d'Hydratation (7j)",
      labelEn: "Heat of Hydration (7-day)",
      unit: "J/g",
      inputType: "number",
      categoryGroup: "hydration",
      requirementLevel: "required",
      testStandard: "EN 196-8 / EN 196-9",
      min: 180,
      max: 450,
      step: 5,
      defaultVal: 290,
      placeholder: "290",
      categoryKey: "cement",
      isRequired: () => true,
      validate: (val) => validateNumericRange(val, 180, 450, "حرارة الإماهة", "Chaleur d'hydratation", "Heat of hydration", "J/g")
    },
    {
      key: "lossOnIgnition",
      propertyId: "PROP_CEM_LOI",
      labelAr: "الفاقد في الحرق (LOI)",
      labelFr: "Perte au Feu (PAF)",
      labelEn: "Loss on Ignition (LOI)",
      unit: "%",
      inputType: "number",
      categoryGroup: "chemical",
      requirementLevel: "required",
      testStandard: "EN 196-2 / ASTM C114",
      min: 0.1,
      max: 7.0,
      step: 0.1,
      defaultVal: 1.8,
      placeholder: "1.8",
      categoryKey: "cement",
      isRequired: () => true,
      validate: (val) => validateNumericRange(val, 0.1, 7.0, "الفاقد في الحرق", "Perte au feu", "Loss on ignition", "%")
    },
    {
      key: "insolubleResidue",
      propertyId: "PROP_CEM_INSOLUBLE",
      labelAr: "الراسب غير القابل للذوبان",
      labelFr: "Résidu Insoluble",
      labelEn: "Insoluble Residue",
      unit: "%",
      inputType: "number",
      categoryGroup: "chemical",
      requirementLevel: "required",
      testStandard: "EN 196-2 / ASTM C114",
      min: 0.1,
      max: 5.0,
      step: 0.1,
      defaultVal: 0.6,
      placeholder: "0.6",
      categoryKey: "cement",
      isRequired: () => true,
      validate: (val) => validateNumericRange(val, 0.1, 5.0, "الراسب غير القابل للذوبان", "Résidu insoluble", "Insoluble residue", "%")
    },
    {
      key: "sulfateContent",
      propertyId: "PROP_CEM_SO3",
      labelAr: "محتوى الكبريتات (SO3)",
      labelFr: "Teneur en Sulfates (SO3)",
      labelEn: "Sulfate Content (SO3)",
      unit: "%",
      inputType: "number",
      categoryGroup: "chemical",
      requirementLevel: "required",
      testStandard: "EN 196-2 / ASTM C114",
      min: 0.5,
      max: 4.5,
      step: 0.1,
      defaultVal: 2.7,
      placeholder: "2.7",
      categoryKey: "cement",
      isRequired: () => true,
      validate: (val) => validateNumericRange(val, 0.5, 4.5, "محتوى الكبريتات", "Teneur en sulfates", "Sulfate content", "%")
    },
    {
      key: "chlorideContent",
      propertyId: "PROP_CEM_CHLORIDE",
      labelAr: "محتوى الكلوريدات (Cl-)",
      labelFr: "Teneur en Chlorures (Cl-)",
      labelEn: "Chloride Content (Cl-)",
      unit: "%",
      inputType: "number",
      categoryGroup: "chemical",
      requirementLevel: "required",
      testStandard: "EN 196-2 / ASTM C114",
      min: 0,
      max: 0.10,
      step: 0.005,
      defaultVal: 0.02,
      placeholder: "0.02",
      categoryKey: "cement",
      isRequired: () => true,
      validate: (val) => validateNumericRange(val, 0, 0.10, "محتوى الكلوريدات", "Teneur en chlorures", "Chloride content", "%", true)
    },
    {
      key: "alkaliEquivalent",
      propertyId: "PROP_CEM_ALKALI",
      labelAr: "مكافئ القلويات (Na2O eq)",
      labelFr: "Équivalent Alcalin (Na2O eq)",
      labelEn: "Equivalent Alkali (Na2O eq)",
      unit: "%",
      inputType: "number",
      categoryGroup: "chemical",
      requirementLevel: "required",
      testStandard: "EN 196-2 / ASTM C114",
      min: 0.1,
      max: 1.5,
      step: 0.05,
      defaultVal: 0.65,
      placeholder: "0.65",
      categoryKey: "cement",
      isRequired: () => true,
      validate: (val) => validateNumericRange(val, 0.1, 1.5, "مكافئ القلويات", "Équivalent alcalin", "Equivalent alkali", "%")
    }
  ]
};
"""

print("Writing make_full_schemas.py test...")
